import { getItemData } from "../items/itemModel.js";
import { getMonsterData } from "../monsters/monsterModel.js";
import { getQuestData } from "../quests/questProgress.js";
import { playerClassesDatabase } from "../data/playerClassesDatabase.js";
import {
  DEFAULT_GAME_OPTIONS,
  gameOptionsUiState,
  SUPPORTED_GAME_LANGUAGES,
} from "../state/gameOptionsState.js";

export const GAME_UI_TEXT = {
  en: {
    play: "PLAY",
    home: "Home",
    game: "Game",
    account: "Account",
    accountAccess: "Enter No Name Yet",
    accountAccessDescription: "Choose how you want to continue your adventure.",
    existingAccount: "I already have an account",
    newAccount: "Create a new account",
    backToAccountAccess: "Back to account access",
    accountName: "Account name",
    accountOrEmail: "Account name or email",
    email: "Email",
    password: "Password",
    login: "Log in",
    register: "Create account",
    logoutAccount: "Log out of account",
    loadingCharacters: "Loading characters...",
    authenticationRequired: "Your account session has expired.",
    invalidCredentials: "Invalid account, email, or password.",
    invalidAccount: "Use 3 to 40 letters, numbers, underscores, or hyphens.",
    invalidEmail: "Enter a valid email address.",
    accountAlreadyExists: "This account already exists.",
    emailAlreadyExists: "This email is already linked to an account.",
    connectionError: "The server could not be reached. Try again.",
    characterOnline: "This character is currently online.",
    tooManyLoginAttempts: "Too many attempts. Wait one minute.",
    googleAuthFailed: "Google sign-in failed. Try again.",
    googleAuthUnavailable: "Google sign-in is currently unavailable.",
    or: "or",
    loadingData: "Preparing game data...",
    loadingRenderer: "Loading graphics...",
    loadingNetwork: "Connecting to the world...",
    loadingNetworkRetrying: "Connection interrupted. Trying again...",
    loadingWorld: "Building the nearby world...",
    loadingInterface: "Preparing your interface...",
    loadingReady: "Entering the world...",
    loadingFailed: "The world could not be loaded.",
    retry: "Retry",
    minimap: "Minimap",
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    centerMinimap: "Center on player",
    floorUp: "View upper floor",
    floorDown: "View lower floor",
    language: "Language",
    english: "English",
    french: "French",
    showFps: "Show FPS",
    showCreatureNames: "Creature names",
    showHealthBars: "Health bars",
    musicEnabled: "Music",
    sfxEnabled: "Sound effects",
    musicVolume: "Music volume",
    sfxVolume: "Effects volume",
    restoreDefaults: "Restore defaults",
    closeOptions: "Close options",
    quests: "Quests",
    closeQuests: "Close quests",
    noQuests: "No quests started.",
    questCompleted: "Completed",
    questStarted: "Started",
    characters: "Characters",
    closeCharacters: "Close characters",
    noCharacters: "No characters created.",
    current: "Current",
    select: "Select",
    delete: "Delete",
    deleteCharacter: (name) => `Delete ${name}`,
    deleteCharacterConfirm: (name) => `Delete ${name}? This cannot be undone.`,
    newCharacter: "New character",
    backToCharacters: "Back to characters",
    sex: "Sex",
    head: "Head",
    body: "Body",
    characterName: "Character name",
    hairColor: "Hair",
    clothesColor: "Clothes",
    pantsColor: "Pants",
    shoesColor: "Shoes",
    create: "Create",
    equipments: "Equipments",
    capacityShort: "Cap",
    follow: "Follow",
    hotkeys: "Spells",
    spells: "Spells",
    closeSpells: "Close spells",
    spellBar: "Spell bar",
    spellWindowHelp: "Tap a spell to cast it, or select Assign and then choose a slot above.",
    spellAssignPrompt: (spellName) => `Choose a slot above for ${spellName}.`,
    mobileSpellBarHelp: "Tap to cast. Hold a slot to reassign it.",
    mobileSpellAssignPrompt: (key) => `Choose a learned spell for slot ${key}.`,
    emptySpellSlot: "Empty spell slot",
    spellSlotLabel: (key, spellName) => `Slot ${key}: ${spellName}`,
    clearSpellSlot: (key) => `Clear spell slot ${key}`,
    learnedSpells: "Learned spells",
    castSpell: "Cast",
    assignSpell: "Assign",
    clearHotkey: "Clear",
    noLearnedSpells: "No spells learned.",
    options: "Options",
    logout: "Logout",
    logoutConfirmTitle: "Leave the game?",
    logoutConfirmText: "Your character will be saved before you leave.",
    fullAttack: "Full Attack",
    balanced: "Balanced",
    fullDefense: "Full Defense",
    stats: "Stats",
    mobileMap: "Map",
    mobileEquipment: "Gear",
    mobileBackpack: "Bag",
    mobileChat: "Chat",
    mobileTorch: "Torch",
    mobileHealth: "HP",
    mobileMana: "MP",
    mobileFood: "FOOD",
    mobileLevel: (level) => `Lv ${level}`,
    playerStatus: "Player status",
    targetStatus: "Target status",
    movementControl: "Movement control",
    closePanel: "Close panel",
    gamePanels: "Game panels",
    combatControls: "Combat controls",
    mobileMenu: "Menu",
    mobileSystem: "System",
    rotateDeviceTitle: "Rotate your phone",
    rotateDeviceText: "This game is played in landscape mode.",
    nameLabel: "Name:",
    healthLabel: "Hp:",
    manaLabel: "Mana:",
    sanityLabel: "Sanity:",
    experienceLabel: "Experience:",
    levelLabel: "Level:",
    magicLabel: "Magic:",
    fistLabel: "Fist Fighting:",
    swordLabel: "Sword Fighting:",
    maceLabel: "Mace Fighting:",
    axeLabel: "Axe Fighting:",
    distanceLabel: "Distance:",
    shieldingLabel: "Shielding:",
    xpRemaining: (amount) => `${amount} XP left to go.`,
    characterSaved: "Character saved.",
    characterSaveFailed: "Unable to save character.",
    currentCharacterSaveFailed: "Unable to save the current character.",
    cannotPlaceItem: "You cannot place this item there.",
    itemNotTopOfStack: "You cannot move this item because another item is on top of it.",
    notEnoughCapacity: "You do not have enough capacity.",
    pvpUnavailable: "PVP is not implemented yet.",
    pvpEnabled: "PVP enabled. Attacking an innocent player will mark you with a skull.",
    pvpDisabled: "PVP disabled.",
    pvpChangeFailed: "Unable to change PVP mode.",
    pvpLockedBySkull: "You cannot disable PVP while you have a skull or are in PVP combat.",
    pvpRequiresBothPlayers: "Enable PVP to attack an innocent player.",
    statusWhiteSkull: "White skull",
    statusRedSkull: "Red skull",
    statusPoisoned: "Poisoned",
    statusBurning: "Burning",
    statusElectrified: "Electrified",
    statusFrozen: "Frozen",
    statusCombatLocked: "In combat - logout delay active",
    statusProtectionZone: "Protection zone",
    youDied: "You died.",
    cannotPourPotion: "You cannot pour this potion there.",
    exhausted: "You are exhausted.",
    splitStack: "Split stack",
    splitAmount: "Amount",
    splitConfirm: "Split",
    splitStackNeedsSpace: "You need an empty slot to split this stack.",
    cancel: "Cancel",
    targetOutOfRange: "Target is out of range.",
    runeBlockedByWall: "You cannot use this rune through a wall.",
    alreadyFull: "You are already full.",
    fullHealth: "You are already at full health.",
    fullMana: "You are already at full mana.",
    torchBurnedOut: "This torch is burned out.",
    torchNeedsPlacement: "Equip or place the torch on the ground before lighting it.",
    noPath: "No path possible.",
    destinationTooFar: "Destination is too far.",
    minimapWrongFloor: "Return to your floor before walking there.",
    targetLost: "Target lost.",
    arrowsRequired: "You need arrows to use this bow.",
    invalidCharacterName: "Use 2 to 20 letters. Spaces, apostrophes and hyphens are allowed.",
    invalidAppearance: "Choose a character appearance.",
    spellWrongClass: "Your class cannot cast this spell.",
    spellNotLearned: "You have not learned this spell.",
    spellMagicLevelRequired: (level) => `You need magic level ${level} to cast this spell.`,
    spellNotEnoughMana: "You do not have enough mana.",
    statusEffectNotActive: "You are not affected by this condition.",
    fieldNotFound: "There is no magical field there.",
    fieldOccupied: "There is already a magical field there.",
    duplicateCharacterName: "A character with this name already exists.",
    characterStorageError: "The character data could not be saved.",
    corruptedSave: "The character data is corrupted.",
    unsupportedSave: "This character save format is not supported.",
    characterNotFound: "This character no longer exists.",
    characterOperationFailed: "The character operation failed.",
    backpackRequired: "You need to equip a backpack.",
    backpackFull: "Your backpack is full.",
    invalidReward: "This chest has an invalid reward configuration.",
    rewardCommitFailed: "The reward could not be added to your backpack.",
    chestOpenFailed: "You cannot open this chest.",
    rewardFallback: "your reward",
    questCompletionLog: (questName, rewardText) => `Quest completed: ${questName}. You received ${rewardText}.`,
    questCompletionFloating: (questName, rewardText) => `Quest completed!\n${questName}\nLoot: ${rewardText}`,
    questAlreadyCompleted: (questName) => `You have already completed ${questName}.`,
    levelAdvanced: (level) => `You advanced to level ${level}.`,
    skillAdvanced: (skill, level) => `Your ${skill} skill advanced to level ${level}.`,
    youSeeProperName: (name) => `You see ${name}.`,
    youSee: (article, name) => `You see ${article} ${name}.`,
    youSeeYourself: (level) => `You see yourself. You are level ${level}.`,
    youSeeYourselfClass: (className, level) => `You see yourself. You are a ${className} level ${level}.`,
    attack: "Attack",
    defense: "Defense",
    itemCharges: (charges) => `It has ${charges} charge${charges > 1 ? "s" : ""}`,
    itemWeight: (weight) => `It weighs ${weight.toFixed(1)} oz.`,
    itemsWeight: (weight) => `They weigh ${weight.toFixed(1)} oz.`,
    unknownItem: "unknown item",
    lootNothing: "Loot: nothing.",
    lootFromNothing: (sourceName) => `Loot from ${sourceName}: nothing.`,
    lootList: (items) => `Loot: ${items}.`,
    lootFromList: (sourceName, items) => `Loot from ${sourceName}: ${items}.`,
    experienceGained: (amount) => `You gained ${amount} experience.`,
    experienceGainedFrom: (amount, sourceName) => `You gained ${amount} experience from ${sourceName}.`,
    damageTaken: (amount, sourceName) => `You took ${amount} damage from ${sourceName}.`,
    damageDealt: (amount, sourceName) => `You dealt ${amount} damage to ${sourceName}.`,
    tileName: "Tile",
    tileDescription: "A tile.",
    localChannel: "Local",
    globalChannel: "Global",
    tradeChannel: "Trade",
    logsChannel: "Logs",
    npcQueue: (name, position) => `${name} asks you to wait. Queue position: ${position}.`,
    sayNpcOption: (speech) => `Say ${speech}`,
    npcOptionsLabel: "You can say:",
  },
  fr: {
    play: "JOUER",
    home: "Accueil",
    game: "Jeu",
    account: "Compte",
    accountAccess: "Entrer dans No Name Yet",
    accountAccessDescription: "Choisis comment tu veux continuer ton aventure.",
    existingAccount: "J'ai deja un compte",
    newAccount: "Creer un nouveau compte",
    backToAccountAccess: "Retour aux options de compte",
    accountName: "Nom du compte",
    accountOrEmail: "Nom du compte ou courriel",
    email: "Courriel",
    password: "Mot de passe",
    login: "Connexion",
    register: "Creer un compte",
    logoutAccount: "Deconnecter le compte",
    loadingCharacters: "Chargement des personnages...",
    authenticationRequired: "Ta session de compte est expiree.",
    invalidCredentials: "Le compte, le courriel ou le mot de passe est invalide.",
    invalidAccount: "Utilise 3 a 40 lettres, chiffres, traits d'union ou tirets bas.",
    invalidEmail: "Entre une adresse courriel valide.",
    accountAlreadyExists: "Ce compte existe deja.",
    emailAlreadyExists: "Ce courriel est deja lie a un compte.",
    connectionError: "Impossible de joindre le serveur. Reessaie.",
    characterOnline: "Ce personnage est deja connecte.",
    tooManyLoginAttempts: "Trop de tentatives. Attends une minute.",
    googleAuthFailed: "La connexion Google a echoue. Reessaie.",
    googleAuthUnavailable: "La connexion Google est indisponible pour le moment.",
    or: "ou",
    loadingData: "Preparation des donnees du jeu...",
    loadingRenderer: "Chargement des graphiques...",
    loadingNetwork: "Connexion au monde...",
    loadingNetworkRetrying: "Connexion interrompue. Nouvelle tentative...",
    loadingWorld: "Construction du monde autour de toi...",
    loadingInterface: "Preparation de ton interface...",
    loadingReady: "Entree dans le monde...",
    loadingFailed: "Le monde n'a pas pu etre charge.",
    retry: "Reessayer",
    minimap: "Mini-carte",
    zoomIn: "Zoom avant",
    zoomOut: "Zoom arriere",
    centerMinimap: "Recentrer sur le joueur",
    floorUp: "Voir l'etage du haut",
    floorDown: "Voir l'etage du bas",
    language: "Langue",
    english: "Anglais",
    french: "Francais",
    showFps: "Afficher les FPS",
    showCreatureNames: "Noms des creatures",
    showHealthBars: "Barres de vie",
    musicEnabled: "Musique",
    sfxEnabled: "Effets sonores",
    musicVolume: "Volume de la musique",
    sfxVolume: "Volume des effets",
    restoreDefaults: "Remettre par defaut",
    closeOptions: "Fermer les options",
    quests: "Quetes",
    closeQuests: "Fermer les quetes",
    noQuests: "Aucune quete commencee.",
    questCompleted: "Terminee",
    questStarted: "Commencee",
    characters: "Personnages",
    closeCharacters: "Fermer les personnages",
    noCharacters: "Aucun personnage cree.",
    current: "Actuel",
    select: "Choisir",
    delete: "Supprimer",
    deleteCharacter: (name) => `Supprimer ${name}`,
    deleteCharacterConfirm: (name) => `Supprimer ${name}? Cette action est irreversible.`,
    newCharacter: "Nouveau personnage",
    backToCharacters: "Retour aux personnages",
    sex: "Sexe",
    head: "Tete",
    body: "Corps",
    characterName: "Nom du personnage",
    hairColor: "Cheveux",
    clothesColor: "Linge",
    pantsColor: "Pantalon",
    shoesColor: "Souliers",
    create: "Creer",
    equipments: "Equipement",
    capacityShort: "Cap",
    follow: "Suivre",
    hotkeys: "Sort",
    spells: "Sorts",
    closeSpells: "Fermer les sorts",
    spellBar: "Barre de sorts",
    spellWindowHelp: "Touche un sort pour le lancer, ou choisis Assigner puis un emplacement en haut.",
    spellAssignPrompt: (spellName) => `Choisis un emplacement en haut pour ${spellName}.`,
    mobileSpellBarHelp: "Touche pour lancer. Maintiens une case pour la reassigner.",
    mobileSpellAssignPrompt: (key) => `Choisis un sort appris pour la case ${key}.`,
    emptySpellSlot: "Emplacement de sort vide",
    spellSlotLabel: (key, spellName) => `Emplacement ${key}: ${spellName}`,
    clearSpellSlot: (key) => `Vider l'emplacement de sort ${key}`,
    learnedSpells: "Sorts appris",
    castSpell: "Lancer",
    assignSpell: "Assigner",
    clearHotkey: "Vider",
    noLearnedSpells: "Aucun sort appris.",
    options: "Options",
    logout: "Quitter",
    logoutConfirmTitle: "Quitter le jeu?",
    logoutConfirmText: "Ton personnage va etre sauvegarde avant de quitter.",
    fullAttack: "Attaque",
    balanced: "Equilibre",
    fullDefense: "Defense",
    stats: "Stats",
    mobileMap: "Carte",
    mobileEquipment: "Equip.",
    mobileBackpack: "Sac",
    mobileChat: "Chat",
    mobileTorch: "Torche",
    mobileHealth: "VIE",
    mobileMana: "MANA",
    mobileFood: "FAIM",
    mobileLevel: (level) => `Niv. ${level}`,
    playerStatus: "Etat du joueur",
    targetStatus: "Etat de la cible",
    movementControl: "Controle du mouvement",
    closePanel: "Fermer le panneau",
    gamePanels: "Panneaux du jeu",
    combatControls: "Controles de combat",
    mobileMenu: "Menu",
    mobileSystem: "Systeme",
    rotateDeviceTitle: "Tourne ton telephone",
    rotateDeviceText: "Le jeu se joue en mode paysage.",
    nameLabel: "Nom:",
    healthLabel: "Vie:",
    manaLabel: "Mana:",
    sanityLabel: "Satiete:",
    experienceLabel: "Experience:",
    levelLabel: "Niveau:",
    magicLabel: "Magie:",
    fistLabel: "Combat a mains nues:",
    swordLabel: "Epee:",
    maceLabel: "Masse:",
    axeLabel: "Hache:",
    distanceLabel: "Distance:",
    shieldingLabel: "Bouclier:",
    xpRemaining: (amount) => `${amount} XP avant le prochain niveau.`,
    characterSaved: "Personnage sauvegarde.",
    characterSaveFailed: "Impossible de sauvegarder le personnage.",
    currentCharacterSaveFailed: "Impossible de sauvegarder le personnage actuel.",
    cannotPlaceItem: "Tu ne peux pas placer cet objet la.",
    itemNotTopOfStack: "Tu ne peux pas deplacer cet objet parce qu'un autre objet est par-dessus.",
    notEnoughCapacity: "Tu n'as pas assez de capacite.",
    pvpUnavailable: "Le PVP n'est pas encore disponible.",
    pvpEnabled: "PVP active. Attaquer un joueur innocent va te donner un skull.",
    pvpDisabled: "PVP desactive.",
    pvpChangeFailed: "Impossible de changer le mode PVP.",
    pvpLockedBySkull: "Tu ne peux pas desactiver le PVP pendant un combat PVP ou tant que tu as un skull.",
    pvpRequiresBothPlayers: "Active le PVP pour attaquer un joueur innocent.",
    statusWhiteSkull: "Skull blanc",
    statusRedSkull: "Skull rouge",
    statusPoisoned: "Empoisonne",
    statusBurning: "En feu",
    statusElectrified: "Electrise",
    statusFrozen: "Gele",
    statusCombatLocked: "En combat - delai de deconnexion actif",
    statusProtectionZone: "Zone de protection",
    youDied: "Tu es mort.",
    cannotPourPotion: "Tu ne peux pas vider cette potion la.",
    exhausted: "Tu es epuise.",
    splitStack: "Separer la pile",
    splitAmount: "Quantite",
    splitConfirm: "Separer",
    splitStackNeedsSpace: "Il te faut une case vide pour separer cette pile.",
    cancel: "Annuler",
    targetOutOfRange: "La cible est trop loin.",
    runeBlockedByWall: "Tu ne peux pas lancer cette rune a travers un mur.",
    alreadyFull: "Tu n'as plus faim.",
    fullHealth: "Ta vie est deja pleine.",
    fullMana: "Ton mana est deja plein.",
    torchBurnedOut: "Cette torche est completement brulee.",
    torchNeedsPlacement: "Equipe la torche ou pose-la au sol avant de l'allumer.",
    noPath: "Aucun chemin possible.",
    destinationTooFar: "La destination est trop loin.",
    minimapWrongFloor: "Reviens a ton etage avant de marcher la.",
    targetLost: "Cible perdue.",
    arrowsRequired: "Il te faut des fleches pour utiliser cet arc.",
    invalidCharacterName: "Utilise de 2 a 20 lettres. Les espaces, apostrophes et tirets sont permis.",
    invalidAppearance: "Choisis une apparence.",
    spellWrongClass: "Ta classe ne peut pas lancer ce sort.",
    spellNotLearned: "Tu n'as pas appris ce sort.",
    spellMagicLevelRequired: (level) => `Il te faut le niveau de magie ${level} pour lancer ce sort.`,
    spellNotEnoughMana: "Tu n'as pas assez de mana.",
    statusEffectNotActive: "Tu n'es pas affecte par cet effet.",
    fieldNotFound: "Il n'y a aucun field magique a cet endroit.",
    fieldOccupied: "Il y a deja un field magique a cet endroit.",
    duplicateCharacterName: "Un personnage porte deja ce nom.",
    characterStorageError: "Les donnees du personnage n'ont pas pu etre sauvegardees.",
    corruptedSave: "La sauvegarde du personnage est corrompue.",
    unsupportedSave: "Ce format de sauvegarde n'est pas supporte.",
    characterNotFound: "Ce personnage n'existe plus.",
    characterOperationFailed: "L'operation sur le personnage a echoue.",
    backpackRequired: "Tu dois equiper un sac.",
    backpackFull: "Ton sac est plein.",
    invalidReward: "La recompense de ce coffre est mal configuree.",
    rewardCommitFailed: "La recompense n'a pas pu etre ajoutee a ton sac.",
    chestOpenFailed: "Tu ne peux pas ouvrir ce coffre.",
    rewardFallback: "ta recompense",
    questCompletionLog: (questName, rewardText) => `Quete terminee: ${questName}. Tu as recu ${rewardText}.`,
    questCompletionFloating: (questName, rewardText) => `Quete terminee!\n${questName}\nButin: ${rewardText}`,
    questAlreadyCompleted: (questName) => `Tu as deja termine ${questName}.`,
    levelAdvanced: (level) => `Tu es maintenant niveau ${level}.`,
    skillAdvanced: (skill, level) => `Ta competence ${skill} est maintenant niveau ${level}.`,
    youSeeProperName: (name) => `Tu vois ${name}.`,
    youSee: (article, name) => `Tu vois ${article} ${name}.`,
    youSeeYourself: (level) => `Tu te vois. Tu es niveau ${level}.`,
    youSeeYourselfClass: (className, level) => `Tu te vois. Tu es ${className}, niveau ${level}.`,
    attack: "Attaque",
    defense: "Defense",
    itemCharges: (charges) => `Il reste ${charges} charge${charges > 1 ? "s" : ""}.`,
    itemWeight: (weight) => `Il pese ${weight.toFixed(1)} oz.`,
    itemsWeight: (weight) => `Ils pesent ${weight.toFixed(1)} oz.`,
    unknownItem: "objet inconnu",
    lootNothing: "Butin: rien.",
    lootFromNothing: (sourceName) => `Butin de ${sourceName}: rien.`,
    lootList: (items) => `Butin: ${items}.`,
    lootFromList: (sourceName, items) => `Butin de ${sourceName}: ${items}.`,
    experienceGained: (amount) => `Tu as gagne ${amount} points d'experience.`,
    experienceGainedFrom: (amount, sourceName) => `Tu as gagne ${amount} points d'experience grace a ${sourceName}.`,
    damageTaken: (amount, sourceName) => `Tu as recu ${amount} degats de ${sourceName}.`,
    damageDealt: (amount, sourceName) => `Tu as inflige ${amount} degats a ${sourceName}.`,
    tileName: "Tuile",
    tileDescription: "Une tuile.",
    localChannel: "Local",
    globalChannel: "Global",
    tradeChannel: "Echange",
    logsChannel: "Journal",
    npcQueue: (name, position) => `${name} te demande d'attendre. Position dans la file : ${position}.`,
    sayNpcOption: (speech) => `Dire ${speech}`,
    npcOptionsLabel: "Tu peux dire :",
  },
};

export const GAME_CONTENT_TEXT = {
  fr: {
    items: {
      apple: { name: "Pomme", pluralName: "Pommes", desc: "Une pomme.", suffix: "une" },
      cheese: { name: "Fromage", pluralName: "Fromages", desc: "Un morceau de fromage.", suffix: "un" },
      box: { name: "Caisse", pluralName: "Caisses", desc: "Une grosse vieille caisse.", suffix: "une" },
      smallBox: { name: "Petite caisse", pluralName: "Petites caisses", desc: "Une petite caisse.", suffix: "une" },
      healthPotion: { name: "Potion de vie", pluralName: "Potions de vie", desc: "Une potion qui redonne de la vie.", suffix: "une" },
      manaPotion: { name: "Potion de mana", pluralName: "Potions de mana", desc: "Une potion qui redonne du mana.", suffix: "une" },
      emptyPotion: { name: "Fiole vide", pluralName: "Fioles vides", desc: "Une fiole vide.", suffix: "une" },
      torch: { name: "Torche", pluralName: "Torches", desc: "Une torche qui eclaire les endroits sombres.", suffix: "une" },
      ratCorpse: { name: "Cadavre de rat", pluralName: "Cadavres de rat", desc: "Un rat mort.", suffix: "un" },
      playerCorpse: { name: "Cadavre de joueur", pluralName: "Cadavres de joueur", desc: "Un joueur mort.", suffix: "un" },
      sword: { name: "Epee", pluralName: "Epees", desc: "Une vieille epee rouillee.", suffix: "une" },
      mace: { name: "Masse", pluralName: "Masses", desc: "Une masse rudimentaire et peu fiable.", suffix: "une" },
      arrow: { name: "Fleche", pluralName: "Fleches", desc: "Une fleche toute simple.", suffix: "une" },
      bow: { name: "Arc", pluralName: "Arcs", desc: "Un arc de chasse de base.", suffix: "un" },
      woodenShield: { name: "Bouclier de bois", pluralName: "Boucliers de bois", desc: "Un vieux bouclier de bois.", suffix: "un" },
      ironShield: { name: "Rempart de fer", pluralName: "Remparts de fer", desc: "Un bouclier fiable forge en fer massif.", suffix: "un" },
      azureGuardShield: { name: "Garde azur", pluralName: "Gardes azur", desc: "Un bouclier bleu porte par les sentinelles aguerries.", suffix: "un" },
      suncrestShield: { name: "Bouclier solaire", pluralName: "Boucliers solaires", desc: "Son embleme de bronze brille comme un petit soleil.", suffix: "un" },
      lionheartShield: { name: "Egide Coeur-de-lion", pluralName: "Egides Coeur-de-lion", desc: "Un bouclier noble marque d'un lion argente.", suffix: "une" },
      dreadShield: { name: "Bouclier du guetteur noir", pluralName: "Boucliers du guetteur noir", desc: "Un bouclier sombre borde de vieil or.", suffix: "un" },
      seraphShield: { name: "Egide du seraphin", pluralName: "Egides du seraphin", desc: "Un bouclier serti de joyaux en forme d'ailes repliees.", suffix: "une" },
      groveShield: { name: "Bouclier du gardien des bois", pluralName: "Boucliers du gardien des bois", desc: "Un bouclier rond beni par une feuille ancienne.", suffix: "un" },
      hideTrousers: { name: "Pantalon de peau brute", pluralName: "Pantalons de peau brute", desc: "Un pantalon lourd cousu dans une peau epaisse.", suffix: "un" },
      wandererPants: { name: "Pantalon du vagabond", pluralName: "Pantalons du vagabond", desc: "Un pantalon simple fait pour les longues routes.", suffix: "un" },
      hunterLeggings: { name: "Jambieres du chasseur", pluralName: "Jambieres du chasseur", desc: "Des jambieres souples renforcees aux genoux.", suffix: "des" },
      chainLeggings: { name: "Jambieres de mailles", pluralName: "Jambieres de mailles", desc: "Des anneaux entrelaces protegent les jambes sans les ralentir.", suffix: "des" },
      knightGreaves: { name: "Grevieres du chevalier", pluralName: "Grevieres du chevalier", desc: "Des grevieres d'acier polies pour la premiere ligne.", suffix: "des" },
      sunforgedGreaves: { name: "Grevieres solaires", pluralName: "Grevieres solaires", desc: "Des grevieres dorees forgees pour un champion royal.", suffix: "des" },
      wornBoots: { name: "Bottes usees", pluralName: "Bottes usees", desc: "De vieilles bottes qui ont traverse bien des routes boueuses.", suffix: "des" },
      leatherBoots: { name: "Bottes de cuir", pluralName: "Bottes de cuir", desc: "Des bottes de cuir solides et confortables.", suffix: "des" },
      ironBoots: { name: "Bottes Pas-de-fer", pluralName: "Bottes Pas-de-fer", desc: "Des bottes plaquees de fer qui frappent le sol avec autorite.", suffix: "des" },
      steelBoots: { name: "Bottes de l'avant-garde", pluralName: "Bottes de l'avant-garde", desc: "Des bottes renforcees portees par les gardes disciplines.", suffix: "des" },
      tidewalkerBoots: { name: "Bottes Marche-maree", pluralName: "Bottes Marche-maree", desc: "Des bottes bleues qui ne semblent jamais rester mouillees.", suffix: "des" },
      sunforgedBoots: { name: "Bottes solaires", pluralName: "Bottes solaires", desc: "Des bottes ornees plaquees d'acier dore.", suffix: "des" },
      leatherArmor: { name: "Armure de cuir", pluralName: "Armures de cuir", desc: "Une armure de cuir classique.", suffix: "une" },
      studdedLeatherArmor: { name: "Manteau cloute du voyageur", pluralName: "Manteaux cloutes du voyageur", desc: "Un manteau de cuir renforce de clous metalliques.", suffix: "un" },
      mercenaryArmor: { name: "Harnais du mercenaire", pluralName: "Harnais du mercenaire", desc: "Du cuir et du fer superposes pour une guerre sans fla-fla.", suffix: "un" },
      steelPlate: { name: "Plastron de l'avant-garde", pluralName: "Plastrons de l'avant-garde", desc: "Un plastron d'acier sombre concu pour tenir la ligne.", suffix: "un" },
      tideforgedArmor: { name: "Cotte forge-maree", pluralName: "Cottes forge-maree", desc: "Une cotte d'acier bleu qui bouge comme l'eau.", suffix: "une" },
      arcanistRobe: { name: "Robe violette de l'arcaniste", pluralName: "Robes violettes de l'arcaniste", desc: "Une robe ornee tissee pour un mage experimente.", suffix: "une" },
      grovekeeperMantle: { name: "Manteau du gardien des bois", pluralName: "Manteaux du gardien des bois", desc: "Un manteau vert mousse qui sent legerement la pluie.", suffix: "un" },
      midnightMantle: { name: "Manteau de minuit", pluralName: "Manteaux de minuit", desc: "Un manteau bleu profond aime des voyants voyageurs.", suffix: "un" },
      ivoryMantle: { name: "Manteau d'ivoire de l'oracle", pluralName: "Manteaux d'ivoire de l'oracle", desc: "Un manteau clair borde d'or ancien.", suffix: "un" },
      wandererHood: { name: "Capuchon du vagabond", pluralName: "Capuchons du vagabond", desc: "Un capuchon use qui garde la poussiere loin des yeux.", suffix: "un" },
      groveHood: { name: "Capuchon des bois", pluralName: "Capuchons des bois", desc: "Un capuchon vert porte par les gardiens silencieux de la foret.", suffix: "un" },
      leatherCap: { name: "Coiffe de cuir cerclee", pluralName: "Coiffes de cuir cerclees", desc: "Une coiffe de cuir renforcee de bandes de fer.", suffix: "une" },
      ironHelm: { name: "Casque de la sentinelle", pluralName: "Casques de la sentinelle", desc: "Un large casque de fer qui protege les joues.", suffix: "un" },
      hornedSteelHelm: { name: "Casque d'acier cornu", pluralName: "Casques d'acier cornus", desc: "Un casque d'acier couronne de deux petites cornes.", suffix: "un" },
      knightGreathelm: { name: "Grand heaume du chevalier", pluralName: "Grands heaumes du chevalier", desc: "Un heaume ferme fait pour les combats brutaux.", suffix: "un" },
      sunforgedHelm: { name: "Heaume-couronne solaire", pluralName: "Heaumes-couronnes solaires", desc: "Un heaume dore muni d'une visiere bleue.", suffix: "un" },
      spiderCorpse: { name: "Cadavre d'araignee", pluralName: "Cadavres d'araignee", desc: "Une araignee morte.", suffix: "un" },
      bag: { name: "Sac", pluralName: "Sacs", desc: "Un sac de 8 cases.", suffix: "un" },
      goldCoin: { name: "Piece d'or", pluralName: "Pieces d'or", desc: "Une piece d'or.", suffix: "une" },
      azureCoin: { name: "Piece de platine", pluralName: "Pieces de platine", desc: "Une piece de platine qui vaut 100 pieces d'or.", suffix: "une" },
      crystalCoin: { name: "Piece de cristal", pluralName: "Pieces de cristal", desc: "Une piece cristalline qui vaut 1 000 pieces d'or.", suffix: "une" },
      fireRune: { name: "Rune de feu", pluralName: "Runes de feu", desc: "Une rune gravee de magie de feu.", suffix: "une" },
      runeSatchel: { name: "Sac de test runique", pluralName: "Sacs de test runique", desc: "Un grand sac prepare pour tester les runes.", suffix: "un" },
      iceRune: { name: "Rune de glace", pluralName: "Runes de glace", desc: "Une rune chargee d'un froid mordant.", suffix: "une" },
      energyRune: { name: "Rune d'energie", pluralName: "Runes d'energie", desc: "Une rune chargee d'energie instable.", suffix: "une" },
      poisonRune: { name: "Rune de poison", pluralName: "Runes de poison", desc: "Une rune imbibee d'un poison virulent.", suffix: "une" },
      smallHealingRune: { name: "Petite rune de soin", pluralName: "Petites runes de soin", desc: "Une rune simple qui redonne un peu de vie.", suffix: "une" },
      greatHealingRune: { name: "Grande rune de soin", pluralName: "Grandes runes de soin", desc: "Une rune puissante qui redonne beaucoup de vie.", suffix: "une" },
      energyFieldRune: { name: "Rune de champ d'energie", pluralName: "Runes de champ d'energie", desc: "Cree un champ d'energie au sol.", suffix: "une" },
      poisonFieldRune: { name: "Rune de champ empoisonne", pluralName: "Runes de champ empoisonne", desc: "Cree un champ empoisonne au sol.", suffix: "une" },
      iceFieldRune: { name: "Rune de champ glace", pluralName: "Runes de champ glace", desc: "Cree un champ glace au sol.", suffix: "une" },
      fireFieldRune: { name: "Rune de champ de feu", pluralName: "Runes de champ de feu", desc: "Cree un champ de feu au sol.", suffix: "une" },
      dissipationRune: { name: "Rune de dissipation", pluralName: "Runes de dissipation", desc: "Brise un champ magique.", suffix: "une" },
    },
    monsters: {
      rat: { name: "Rat", desc: "Un petit rat feroce.", suffix: "un" },
      spider: { name: "Araignee", desc: "Une araignee venimeuse.", suffix: "une" },
    },
    classes: {
      noClass: { name: "Sans classe" },
      knight: { name: "Chevalier" },
      archer: { name: "Archer" },
      mage: { name: "Mage" },
      priest: { name: "Pretre" },
    },
    appearances: {
      male: { label: "Garcon" },
      female: { label: "Fille" },
    },
    quests: {
      tiro_cave_spider_treasure: {
        name: "Tresor de la caverne aux araignees",
        description: "Tu as trouve le tresor cache dans la caverne aux araignees.",
      },
    },
  },
};

export const getCurrentGameLanguage = () => {
  const language = gameOptionsUiState.values.language;
  return SUPPORTED_GAME_LANGUAGES.has(language) ? language : DEFAULT_GAME_OPTIONS.language;
};

export const getGameUiText = (textKey) => {
  const language = getCurrentGameLanguage();
  return GAME_UI_TEXT[language]?.[textKey] ?? GAME_UI_TEXT.en[textKey] ?? textKey;
};

export const getLocalizedContentDataForLanguage = (contentType, contentId, fallbackData, language) => {
  const localizedData = GAME_CONTENT_TEXT[language]?.[contentType]?.[contentId];
  return localizedData ? { ...fallbackData, ...localizedData } : fallbackData;
};

export const getLocalizedContentData = (contentType, contentId, fallbackData) => {
  return getLocalizedContentDataForLanguage(contentType, contentId, fallbackData, getCurrentGameLanguage());
};

export const getLocalizedItemDataForLanguage = (itemId, language) => {
  const itemData = getItemData(itemId);
  return itemData ? getLocalizedContentDataForLanguage("items", itemId, itemData, language) : null;
};

export const getLocalizedItemData = (itemId) => {
  const itemData = getItemData(itemId);
  return itemData ? getLocalizedContentData("items", itemId, itemData) : null;
};

export const getLocalizedMonsterData = (monsterId) => {
  const monsterData = getMonsterData(monsterId);
  return monsterData ? getLocalizedContentData("monsters", monsterId, monsterData) : null;
};

export const getLocalizedClassData = (classId) => {
  const classData = playerClassesDatabase[classId];
  return classData ? getLocalizedContentData("classes", classId, classData) : null;
};

export const getLocalizedQuestData = (questId) => {
  const questData = getQuestData(questId);
  return questData ? getLocalizedContentData("quests", questId, questData) : null;
};

export const getLocalizedItemName = (itemId, quantity = 1) => {
  return getLocalizedItemNameForLanguage(itemId, quantity, getCurrentGameLanguage());
};

export const getLocalizedItemNameForLanguage = (itemId, quantity = 1, language = "en") => {
  const itemData = getLocalizedItemDataForLanguage(itemId, language);
  if (!itemData) {
    return itemId;
  }
  if (quantity > 1) {
    return itemData.pluralName ?? `${itemData.name}s`;
  }
  return itemData.name;
};

export const getLocalizedSkillName = (skillKey) => {
  const textKeyBySkill = {
    magic: "magicLabel",
    fist: "fistLabel",
    sword: "swordLabel",
    mace: "maceLabel",
    axe: "axeLabel",
    distance: "distanceLabel",
    shielding: "shieldingLabel",
  };
  const label = getGameUiText(textKeyBySkill[skillKey]);
  return typeof label === "string" ? label.replace(":", "").toLowerCase() : skillKey;
};
