export const spellsDatabase = {
  lux: {
    spellId: "lux",
    name: "Light",
    nameFr: "Lumiere",
    description: "Creates a magical light around you.",
    descriptionFr: "Cree une lumiere magique autour de toi.",
    incantation: "Lux",
    learnedByDefault: true,
    learnPrice: 0,
    allowedClassIds: null,
    requiredMagicLevel: 0,
    manaCost: 5,
    cooldownGroup: "magic",
    action: "lightSelf",
    durationMs: 180000,
    lightRadius: 340,
    effectColor: 0xffd86b,
  },
  cura: {
    spellId: "cura",
    name: "Healing Spell",
    nameFr: "Sort de soin",
    description: "Restores some of your health.",
    descriptionFr: "Redonne une partie de ta vie.",
    incantation: "Cura",
    learningKeywords: [
      "heal",
      "heals",
      "healing",
      "healing spell",
      "healing spells",
      "soin",
      "soins",
      "sort de soin",
      "sorts de soin",
    ],
    learnedByDefault: false,
    learnPrice: 40,
    allowedClassIds: null,
    requiredMagicLevel: 1,
    manaCost: 20,
    cooldownGroup: "magic",
    action: "healSelf",
    power: {
      min: 14,
      max: 20,
      magicLevelMultiplier: 0.8,
      levelMultiplier: 0.2,
    },
    textType: "heal",
    effectColor: 0x72e09a,
  },
};
