export const spellsDatabase = {
  lux: {
    spellId: "lux",
    name: "Light",
    nameFr: "Lumiere",
    description: "Creates a magical light around you.",
    descriptionFr: "Cree une lumiere magique autour de toi.",
    incantation: "Lux",
    learnedByDefault: true,
    learnPrice: 0,
    allowedClassIds: null,
    requiredMagicLevel: 0,
    manaCost: 5,
    cooldownGroup: "spell",
    action: "lightSelf",
    durationMs: 180000,
    lightRadius: 340,
    effectColor: 0xffd86b,
  },
  cura: {
    spellId: "cura",
    name: "Healing Spell",
    nameFr: "Sort de soin",
    description: "Restores some of your health.",
    descriptionFr: "Redonne une partie de ta vie.",
    incantation: "Cura",
    learningKeywords: [
      "heal",
      "heals",
      "healing",
      "healing spell",
      "healing spells",
      "soin",
      "soins",
      "sort de soin",
      "sorts de soin",
    ],
    learnedByDefault: false,
    learnPrice: 40,
    allowedClassIds: null,
    requiredMagicLevel: 1,
    manaCost: 20,
    cooldownGroup: "spell",
    action: "healSelf",
    power: {
      min: 14,
      max: 20,
      magicLevelMultiplier: 0.8,
      levelMultiplier: 0.2,
    },
    textType: "heal",
    effectColor: 0x72e09a,
  },
  purgaFlamma: {
    spellId: "purgaFlamma",
    name: "Fire Cure",
    nameFr: "Soin des brulures",
    description: "Extinguishes magical fire affecting your body.",
    descriptionFr: "Eteint le feu magique qui t'affecte.",
    incantation: "Purga Flamma",
    learnedByDefault: true,
    learnPrice: 0,
    allowedClassIds: null,
    requiredMagicLevel: 1,
    manaCost: 15,
    cooldownGroup: "spell",
    action: "cureStatusEffect",
    statusEffectId: "burning",
    effectColor: 0xff8b3d,
  },
  purgaVenenum: {
    spellId: "purgaVenenum",
    name: "Poison Cure",
    nameFr: "Soin du poison",
    description: "Purges poison from your body.",
    descriptionFr: "Retire le poison de ton corps.",
    incantation: "Purga Venenum",
    learnedByDefault: true,
    learnPrice: 0,
    allowedClassIds: null,
    requiredMagicLevel: 1,
    manaCost: 15,
    cooldownGroup: "spell",
    action: "cureStatusEffect",
    statusEffectId: "poison",
    effectColor: 0x69d84f,
  },
  purgaFulmen: {
    spellId: "purgaFulmen",
    name: "Energy Cure",
    nameFr: "Soin de l'energie",
    description: "Dissipates harmful energy from your body.",
    descriptionFr: "Dissipe l'energie dangereuse de ton corps.",
    incantation: "Purga Fulmen",
    learnedByDefault: true,
    learnPrice: 0,
    allowedClassIds: null,
    requiredMagicLevel: 1,
    manaCost: 15,
    cooldownGroup: "spell",
    action: "cureStatusEffect",
    statusEffectId: "electrified",
    effectColor: 0x9b7cff,
  },
  purgaGelu: {
    spellId: "purgaGelu",
    name: "Frost Cure",
    nameFr: "Soin du gel",
    description: "Breaks the magical frost affecting your body.",
    descriptionFr: "Brise le gel magique qui t'affecte.",
    incantation: "Purga Gelu",
    learnedByDefault: true,
    learnPrice: 0,
    allowedClassIds: null,
    requiredMagicLevel: 1,
    manaCost: 15,
    cooldownGroup: "spell",
    action: "cureStatusEffect",
    statusEffectId: "frozen",
    effectColor: 0x72d9ff,
  },
};
